
sudo mount --bind /repo2/gpdb6/covid/data_seg_0 /data/gpdb/gpdb6/gpdb6_db_seg_10/_data/data/gpdata1/covid0 
sudo mount --bind /repo2/gpdb6/covid/data_seg_1 /data/gpdb/gpdb6/gpdb6_db_seg_10/_data/data/gpdata2/covid1 
sudo mount --bind /repo2/gpdb6/covid/data_seg_2 /data/gpdb/gpdb6/gpdb6_db_seg_11/_data/data/gpdata1/covid2 
sudo mount --bind /repo2/gpdb6/covid/data_seg_3 /data/gpdb/gpdb6/gpdb6_db_seg_11/_data/data/gpdata2/covid3 
sudo mount --bind /repo2/gpdb6/covid/data_seg_4 /data/gpdb/gpdb6/gpdb6_db_seg_12/_data/data/gpdata1/covid4 
sudo mount --bind /repo2/gpdb6/covid/data_seg_5 /data/gpdb/gpdb6/gpdb6_db_seg_12/_data/data/gpdata2/covid5 
sudo mount --bind /repo2/gpdb6/covid/data_seg_6 /data/gpdb/gpdb6/gpdb6_db_seg_13/_data/data/gpdata1/covid6 
sudo mount --bind /repo2/gpdb6/covid/data_seg_7 /data/gpdb/gpdb6/gpdb6_db_seg_13/_data/data/gpdata2/covid7 
sudo mount --bind /repo2/gpdb6/covid/data_seg_8 /data/gpdb/gpdb6/gpdb6_db_seg_14/_data/data/gpdata1/covid8 
sudo mount --bind /repo2/gpdb6/covid/data_seg_9 /data/gpdb/gpdb6/gpdb6_db_seg_14/_data/data/gpdata2/covid9 
sudo mount --bind /repo2/gpdb6/covid/data_seg_10 /data/gpdb/gpdb6/gpdb6_db_seg_15/_data/data/gpdata1/covid10
sudo mount --bind /repo2/gpdb6/covid/data_seg_11 /data/gpdb/gpdb6/gpdb6_db_seg_15/_data/data/gpdata2/covid11
sudo mount --bind /repo2/gpdb6/covid/data_seg_12 /data/gpdb/gpdb6/gpdb6_db_seg_16/_data/data/gpdata1/covid12
sudo mount --bind /repo2/gpdb6/covid/data_seg_13 /data/gpdb/gpdb6/gpdb6_db_seg_16/_data/data/gpdata2/covid13
sudo mount --bind /repo2/gpdb6/covid/data_seg_14 /data/gpdb/gpdb6/gpdb6_db_seg_17/_data/data/gpdata1/covid14
sudo mount --bind /repo2/gpdb6/covid/data_seg_15 /data/gpdb/gpdb6/gpdb6_db_seg_17/_data/data/gpdata2/covid15
sudo mount --bind /repo2/gpdb6/covid/data_seg_16 /data/gpdb/gpdb6/gpdb6_db_seg_18/_data/data/gpdata1/covid16
sudo mount --bind /repo2/gpdb6/covid/data_seg_17 /data/gpdb/gpdb6/gpdb6_db_seg_18/_data/data/gpdata2/covid17
sudo mount --bind /repo2/gpdb6/covid/data_seg_18 /data/gpdb/gpdb6/gpdb6_db_seg_19/_data/data/gpdata1/covid18
sudo mount --bind /repo2/gpdb6/covid/data_seg_19 /data/gpdb/gpdb6/gpdb6_db_seg_19/_data/data/gpdata2/covid19
sudo mount --bind /repo2/gpdb6/covid/data_seg_20 /data/gpdb/gpdb6/gpdb6_db_seg_1/_data/data/gpdata1/covid20
sudo mount --bind /repo2/gpdb6/covid/data_seg_21 /data/gpdb/gpdb6/gpdb6_db_seg_1/_data/data/gpdata2/covid21
sudo mount --bind /repo2/gpdb6/covid/data_seg_22 /data/gpdb/gpdb6/gpdb6_db_seg_20/_data/data/gpdata1/covid22
sudo mount --bind /repo2/gpdb6/covid/data_seg_23 /data/gpdb/gpdb6/gpdb6_db_seg_20/_data/data/gpdata2/covid23
sudo mount --bind /repo2/gpdb6/covid/data_seg_24 /data/gpdb/gpdb6/gpdb6_db_seg_2/_data/data/gpdata1/covid24
sudo mount --bind /repo2/gpdb6/covid/data_seg_25 /data/gpdb/gpdb6/gpdb6_db_seg_2/_data/data/gpdata2/covid25
sudo mount --bind /repo2/gpdb6/covid/data_seg_26 /data/gpdb/gpdb6/gpdb6_db_seg_3/_data/data/gpdata1/covid26
sudo mount --bind /repo2/gpdb6/covid/data_seg_27 /data/gpdb/gpdb6/gpdb6_db_seg_3/_data/data/gpdata2/covid27
sudo mount --bind /repo2/gpdb6/covid/data_seg_28 /data/gpdb/gpdb6/gpdb6_db_seg_4/_data/data/gpdata1/covid28
sudo mount --bind /repo2/gpdb6/covid/data_seg_29 /data/gpdb/gpdb6/gpdb6_db_seg_4/_data/data/gpdata2/covid29
sudo mount --bind /repo2/gpdb6/covid/data_seg_30 /data/gpdb/gpdb6/gpdb6_db_seg_5/_data/data/gpdata1/covid30
sudo mount --bind /repo2/gpdb6/covid/data_seg_31 /data/gpdb/gpdb6/gpdb6_db_seg_5/_data/data/gpdata2/covid31
sudo mount --bind /repo2/gpdb6/covid/data_seg_32 /data/gpdb/gpdb6/gpdb6_db_seg_6/_data/data/gpdata1/covid32
sudo mount --bind /repo2/gpdb6/covid/data_seg_33 /data/gpdb/gpdb6/gpdb6_db_seg_6/_data/data/gpdata2/covid33
sudo mount --bind /repo2/gpdb6/covid/data_seg_34 /data/gpdb/gpdb6/gpdb6_db_seg_7/_data/data/gpdata1/covid34
sudo mount --bind /repo2/gpdb6/covid/data_seg_35 /data/gpdb/gpdb6/gpdb6_db_seg_7/_data/data/gpdata2/covid35
sudo mount --bind /repo2/gpdb6/covid/data_seg_36 /data/gpdb/gpdb6/gpdb6_db_seg_8/_data/data/gpdata1/covid36
sudo mount --bind /repo2/gpdb6/covid/data_seg_37 /data/gpdb/gpdb6/gpdb6_db_seg_8/_data/data/gpdata2/covid37
sudo mount --bind /repo2/gpdb6/covid/data_seg_38 /data/gpdb/gpdb6/gpdb6_db_seg_9/_data/data/gpdata1/covid38
sudo mount --bind /repo2/gpdb6/covid/data_seg_39 /data/gpdb/gpdb6/gpdb6_db_seg_9/_data/data/gpdata2/covid39

